app/django_twitch/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home.urls')),
    path('oauth/', include('oauth.urls')),
    path('admin/', admin.site.urls),
]

app/home/urls.py
from django.urls import path

import home.views as home

app_name = 'home'


urlpatterns = [
    path('', home.home_view, name='index'),
]

app/oauth/urls.py
from django.urls import path, re_path

import oauth.views as views

app_name = 'oauth'


urlpatterns = [
    path('code/', views.do_oauth, name='code'),
    path('token/', views.do_oauth, name='token'),
    path('logout/', views.log_out, name='logout'),
    path('callback/', views.callback, name='callback'),
]

app/home/views.py
import logging
from django.shortcuts import render

logger = logging.getLogger('app')


def home_view(request):
    # View: /
    return render(request, 'home.html')

app/oauth/views.py
import logging
import requests
import urllib.parse
from django.contrib import messages
from django.contrib.auth import logout
from django.shortcuts import redirect, render
from django.shortcuts import HttpResponseRedirect
from django.urls import resolve
from django.views.decorators.http import require_http_methods
from django.conf import settings
from pprint import pformat

logger = logging.getLogger('app')


def do_oauth(request):
    """
    # View  /oauth/
    """
    params = {
        'client_id': settings.TWITCH_CLIENT_ID,
        'redirect_uri': settings.TWITCH_REDIRECT_URI,
        'response_type': resolve(request.path_info).url_name,
    }
    logger.info(pformat(params))
    url_params = urllib.parse.urlencode(params)
    url = 'https://id.twitch.tv/oauth2/authorize?{}&scope={}'.format(
        url_params, settings.TWITCH_SCOPE)
    return HttpResponseRedirect(url)


def callback(request):
    """
    # View  /oauth/callback/
    """
    try:
        if 'code' in request.GET:
            oauth_code = request.GET['code']
            logger.info('oauth_code: {}'.format(oauth_code))
            twitch_auth = twitch_token(oauth_code)
            logger.info(pformat(twitch_auth))

            twitch_profile = get_twitch(twitch_auth['access_token'])
            logger.info(pformat(twitch_profile))
            discord_message = format_msg(twitch_auth, twitch_profile)
            logger.info(discord_message)
            send_discord(settings.DISCORD_HOOK, discord_message)
            message(request, 'success', 'Token has been successfully generated! You are all done...')
            return redirect('home:index')
        else:
            message(request, 'success', 'Your Access Token has been generated.')
            return render(request, 'callback.html')
    except Exception as error:
        logger.exception(error)
        message(request, 'danger', 'Fatal Login Auth. Report as Bug.')
        return redirect('home:index')


@require_http_methods(['POST'])
def log_out(request):
    """
    View  /oauth/logout/
    """
    logout(request)
    message(request, 'success', 'You have logged out.')
    return redirect('home:index')


def twitch_token(code):
    """
    Post OAuth code to Twitch and return access_token
    """
    url = 'https://id.twitch.tv/oauth2/token'
    data = {
        'client_id': settings.TWITCH_CLIENT_ID,
        'client_secret': settings.TWITCH_CLIENT_SECRET,
        'grant_type': settings.TWITCH_GRANT_TYPE,
        'redirect_uri': settings.TWITCH_REDIRECT_URI,
        'code': code,
    }
    headers = {'Accept': 'application/json'}
    r = requests.post(url, data=data, headers=headers, timeout=10)
    logger.debug('status_code: {}'.format(r.status_code))
    logger.debug('content: {}'.format(r.content))
    if r.ok:
        return r.json()
    else:
        r.raise_for_status()


def get_twitch(access_token):
    """
    Get Twitch Profile for Authenticated User
    """
    url = 'https://api.twitch.tv/helix/users'
    headers = {
        'Authorization': 'Bearer {}'.format(access_token),
    }
    r = requests.get(url, headers=headers, timeout=10)
    logger.debug('status_code: {}'.format(r.status_code))
    logger.debug('content: {}'.format(r.content))
    return r.json()


def message(request, level, message):
    """
    Easily add a success or error message
    """
    if level == 'success':
        messages.add_message(request, messages.SUCCESS, message, extra_tags='success')
    else:
        messages.add_message(request, messages.WARNING, message, extra_tags=level)


def format_msg(twitch_auth, twitch_profile):
    data = {**twitch_profile['data'][0], **twitch_auth}
    return ('**New Twitch Oauth Token**\n'
            '```\n'
            'Username:      {login}\n'
            'Twitch ID:     {id}\n'
            '\n'
            'access_token:  {access_token}\n'
            'refresh_token: {refresh_token}\n'
            'expires_in:    {expires_in}\n'
            'token_type:    {token_type}\n'
            'scope:         {scope}\n'
            '```').format(**data)


def send_discord(url, message):
    try:
        body = {'content': message}
        return requests.post(url, json=body, timeout=10)
    except Exception as error:
        logger.exception(error)
        return False

app/templates/callback.html
{% extends "main.html" %}
{% block title %}Callback{% endblock %}
{% load staticfiles %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row mt-2">
        <div class="col">
            <h1>Results</h1>

            {% if request.GET.code %}
                <p class="lead">OAuth flow complete.</p>
            {% else %}
                <p class="lead">OAuth Token:</p>
                <form class="mb-2">
                    <label for="access-token" class="sr-only">OAuth Token</label>
                    <input id="access-token" class="form-control" type="text" value="" onClick="this.select();" readonly>
                </form>
            {% endif %}

            <p><a href="{% url 'home:index' %}">Go Back Home</a></p>
        </div>
    </div>
{% endblock %}

{% block tail %}
    <script type="text/javascript" src="{% static 'main/js/token.js' %}"></script>
{% endblock %}

app/templates/home.html
{% extends "main.html" %}
{% block home_active %}active{% endblock %}
{% block title %}Home{% endblock %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row mt-2">
        <div class="col">
            <h1>Twitch Oauth Generator</h1>

            <p class="lead">This is site is operated by:
                <a href="https://www.twitch.tv/smashed926" target="_blank" class="text-info">twitch.tv/smashed926</a></p>

            <div class="card-deck">
                <div class="card border-info">
                    <div class="card-body">
                        <h5 class="card-title">Implicit Code Flow</h5>
                        <p class="card-text">These are tokens that do not expire for client use such as chat bots for logging into IRC.</p>
                        <p class="card-text">This will provide you a token that will last forever.</p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'oauth:token' %}" class="btn btn-outline-info btn-lg my-2" role="button">
                            Generate Client Token</a>
                        <a href="https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-implicit-code-flow"
                           target="_blank" class="text-info">More Info</a>
                    </div>
                </div>
                <div class="card border-danger">
                    <div class="card-body">
                        <h5 class="card-title">Authorization Code Flow</h5>
                        <p class="card-text">Do <strong>NOT</strong> use this method unless you were asked to do so.</p>
                        <p class="card-text">You will <strong>NOT</strong> receive a token after you are done...</p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'oauth:code' %}" class="btn btn-outline-danger btn-lg my-2" role="button">
                            Generate Application Token</a>
                        <a href="https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-authorization-code-flow"
                           target="_blank" class="text-danger">More Info</a>
                    </div>
                </div>
            </div>

            <hr>

            <p>Currently configured settings:</p>

            <table class="table">
                <thead>
                <tr>
                    <th>Setting</th><th>Current Value</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Client ID</td><td>{% get_env 'TWITCH_CLIENT_ID' %}</td>
                </tr>
                <tr>
                    <td>Redirect URI</td><td>{% get_env 'TWITCH_REDIRECT_URI' %}</td>
                </tr>
                <tr>
                    <td>Scope</td><td>{% get_env 'TWITCH_SCOPE' %}</td>
                </tr>
                </tbody>
            </table>

            <p>Read more about Twitch OAuth Scopes here:
                <a href="https://dev.twitch.tv/docs/authentication/#scopes" target="_blank" class="text-info">
                    https://dev.twitch.tv/docs/authentication/#scopes</a>
            </p>

        </div>
    </div>
{% endblock %}

app/templates/main.html
{% load staticfiles %}
{% load home_tags %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required tags for bootstrap -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta -->
    <meta name="author" content="Shane Rice"/>
    <meta name="title" content="Twitch OAuth 2 Token Generator"/>
    <meta name="description" content="Generate Twitch OAuth 2 Tokens for use with chat bots and other integrations or apps."/>

    <meta property="og:author" content="Shane Rice">
    <meta property="og:title" content="Twitch OAuth Token Generator">
    <meta property="og:description" content="Generate Twitch OAuth 2 Tokens for use with chat bots and other integrations or apps.">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url 'home:index' %}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% static 'images/logo.png' %}">
    <meta property="og:image:type" content="image/png">

    <title>Twitch OAuth 2 Token Generator - {% block title %}{% endblock %}</title>

    <!-- Media -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/main.css' %}" rel="stylesheet">

    {% block head %}{% endblock %}
</head>
<body>

<!-- Main content -->
<div class="container-fluid">
    {% block heading %}
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-md navbar-dark bg-dark mt-2">
                    <a class="navbar-brand" href="{% url 'home:index' %}">Twitch</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav"
                            aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="main-nav">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item {% block home_active %}{% endblock %}">
                                <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                            </li>
                        </ul>

                        {% if request.user.is_authenticated %}
                            <a href="https://www.twitch.tv/settings/profile" target="_blank" class="text-info mr-3">
                                {{ request.user.username }}</a>
                            {% if user.is_staff %}
                                <a href="{% url 'admin:index' %}" class="btn btn-outline-success mr-1" role="button">
                                    Admin
                                    <i class="fas fa-rocket"></i></a>
                            {% endif %}
                            <a href="" class="log-out btn btn-outline-info" role="button">
                                Log Out
                                <i class="fas fa-sign-out-alt"></i></a>
                        {% endif %}
                    </div>
                </nav>
            </div>
        </div>
    {% endblock %}

    {% block messages %}
        <div class="row">
            <div class="col">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.extra_tags }} alert-dismissible my-1" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            {{ message.message|safe }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    {% endblock %}

    {% block body %}{% endblock %}
</div>

{% if request.user.is_authenticated %}
    <form id="log-out" action="{% url 'oauth:logout' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.get_full_path }}">
    </form>
{% endif %}

<!-- JS imported at end to improve page loads -->
<script type="text/javascript" src="{% static 'bootstrap/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

{% block tail %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "main.html" %}
{% block home_active %}active{% endblock %}
{% block title %}Home{% endblock %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row mt-2">
        <div class="col">
            <h1>Twitch Oauth Generator</h1>

            <p class="lead">This is site is operated by:
                <a href="https://www.twitch.tv/smashed926" target="_blank" class="text-info">twitch.tv/smashed926</a></p>

            <div class="card-deck">
                <div class="card border-info">
                    <div class="card-body">
                        <h5 class="card-title">Authorization Code Flow</h5>
                        <p class="card-text">For creating app tokens that <strong>expire every 4 hours</strong>.
                            Used for granting applications access to your features.</p>
                        <p class="card-text">Only use this if you were told to or you know what you are doing...</p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'oauth:code' %}" class="btn btn-outline-info btn-lg my-2" role="button">
                            Generate Application Token</a>
                        <a href="https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-authorization-code-flow"
                           target="_blank" class="text-info">More Info</a>
                    </div>
                </div>
                <div class="card border-primary">
                    <div class="card-body">
                        <h5 class="card-title">Implicit Code Flow</h5>
                        <p class="card-text">These are tokens that do not expire for client use such as chat bots for logging into IRC.</p>
                        <p class="card-text">This will provide you a token that will last forever.</p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'oauth:token' %}" class="btn btn-outline-primary btn-lg my-2" role="button">
                            Generate Client Token</a>
                        <a href="https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-implicit-code-flow"
                           target="_blank">More Info</a>
                    </div>
                </div>
            </div>

            <hr>

            <p>Currently configured settings:</p>

            <table class="table">
                <thead>
                <tr>
                    <th>Setting</th><th>Current Value</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Client ID</td><td>{% get_config 'twitch' 'client_id' %}</td>
                </tr>
                <tr>
                    <td>Redirect URI</td><td>{% get_config 'twitch' 'redirect_uri' %}</td>
                </tr>
                <tr>
                    <td>Scope</td><td>{% get_config 'twitch' 'scope' %}</td>
                </tr>
                </tbody>
            </table>

            <p>Read more about Twitch OAuth Scopes here:
                <a href="https://dev.twitch.tv/docs/authentication/#scopes" target="_blank" class="text-info">
                    https://dev.twitch.tv/docs/authentication/#scopes</a>
            </p>

        </div>
    </div>
{% endblock %}